### ISSUE TITLE
Remove dependency for PHPMyAdmin

### ISSUE THREAD

**Issue by My6UoT9** [inquid/yii2-enhanced-gii#25]
**Is your feature request related to a problem? Please describe.**
On trying to use it this enhanced Gii, I get the following exception:

> Database Error SQLSTATE[42S02]: Base table or view not found: 1146 Table 'phpmyadmin.pma__column_info' doesn't exist
> The SQL being executed was: SELECT comment
> FROM phpmyadmin.pma__column_info
> WHERE db_name='database';

**Describe the solution you'd like**
Something which does not require having PHPMyAdmin installed and giving access rights to it on top. MySQL itself has all the information which is required.

**Comment by gogl92** [comment]
Hi, this issue is very valid. Let me tell you why we did this, the idea of this project is to create whole modules that can be used in production really fast so we use:

The comment of the column: as the name that will be shown to the user instead of the column name, this is supported by MySQL.
The comment of the table: is the field that will be shown as the title of multiple pages inside the CRUD, this is partially supported by MySQL using the INFORMATION_SCHEMA database and the column TABLES.
The comment of the database: we wanted to show a title in the module using the comment of the database, but the problem is that this is not supported by MySQL but phpMyAdmin does something similar to this, using a custom database that phpMyAdmin creates.

The problem, we cannot depend on phpMyAdmin features, neither the MySQL if we want to support multiple database engines.

I will catch the exception if it cannot find the phpMyAdmin database/table and return an empty string to avoid getting that exception, I will think for a long term solution any comments or suggestions are welcome.

**Comment by gogl92** [comment]
Please check if this help you to use the project.

**Comment by My6UoT9** [comment]
Thanks you for the quick update!

I believev the best approach would be, to **try** to automatically gather those informations, if that fails allow the user to provide it. Or maybe through a config beforehand.
One more variant, create from the databasename a "comment" , but I doubt that is gona be very helpfull; colums are often more verbose in the naming (Like job_id => "Job ID") - while database name can even be random strings.

**Comment by My6UoT9** [comment]
It works.

**Comment by gogl92** [comment]
Perfect I will keep the issue open in case it needs additional changes
